//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IVANGenXMLClient.IVANGenXMLService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenXML_D01OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::IVANGenXMLClient.Properties.Settings.Default.IVANGenXMLClient_IVANGenXMLService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenXML_D01CompletedEventHandler GenXML_D01Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenXML_D01", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MsgResult GenXML_D01([System.Xml.Serialization.XmlElementAttribute("D01-TS", IsNullable=true)] D01TS D01TS) {
            object[] results = this.Invoke("GenXML_D01", new object[] {
                        D01TS});
            return ((MsgResult)(results[0]));
        }
        
        /// <remarks/>
        public void GenXML_D01Async(D01TS D01TS) {
            this.GenXML_D01Async(D01TS, null);
        }
        
        /// <remarks/>
        public void GenXML_D01Async(D01TS D01TS, object userState) {
            if ((this.GenXML_D01OperationCompleted == null)) {
                this.GenXML_D01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenXML_D01OperationCompleted);
            }
            this.InvokeAsync("GenXML_D01", new object[] {
                        D01TS}, this.GenXML_D01OperationCompleted, userState);
        }
        
        private void OnGenXML_D01OperationCompleted(object arg) {
            if ((this.GenXML_D01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenXML_D01Completed(this, new GenXML_D01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class D01TS {
        
        private NoiDung noiDungField;
        
        /// <remarks/>
        public NoiDung NoiDung {
            get {
                return this.noiDungField;
            }
            set {
                this.noiDungField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NoiDung {
        
        private string tenBangKeField;
        
        private string kemTheoField;
        
        private ThongTin[] bangKeField;
        
        /// <remarks/>
        public string TenBangKe {
            get {
                return this.tenBangKeField;
            }
            set {
                this.tenBangKeField = value;
            }
        }
        
        /// <remarks/>
        public string KemTheo {
            get {
                return this.kemTheoField;
            }
            set {
                this.kemTheoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ThongTin[] BangKe {
            get {
                return this.bangKeField;
            }
            set {
                this.bangKeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ThongTin {
        
        private string sTTField;
        
        private string hoTenField;
        
        private string masoBHXHField;
        
        private string tenLoaiVanBanField;
        
        private string soVanBanField;
        
        private System.DateTime ngayBanHanhField;
        
        private System.DateTime ngayHieuLucField;
        
        private string coQuanBanHanhField;
        
        private string trichYeuField;
        
        private string noiDungThamDinhField;
        
        /// <remarks/>
        public string STT {
            get {
                return this.sTTField;
            }
            set {
                this.sTTField = value;
            }
        }
        
        /// <remarks/>
        public string HoTen {
            get {
                return this.hoTenField;
            }
            set {
                this.hoTenField = value;
            }
        }
        
        /// <remarks/>
        public string MasoBHXH {
            get {
                return this.masoBHXHField;
            }
            set {
                this.masoBHXHField = value;
            }
        }
        
        /// <remarks/>
        public string TenLoaiVanBan {
            get {
                return this.tenLoaiVanBanField;
            }
            set {
                this.tenLoaiVanBanField = value;
            }
        }
        
        /// <remarks/>
        public string SoVanBan {
            get {
                return this.soVanBanField;
            }
            set {
                this.soVanBanField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayBanHanh {
            get {
                return this.ngayBanHanhField;
            }
            set {
                this.ngayBanHanhField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NgayHieuLuc {
            get {
                return this.ngayHieuLucField;
            }
            set {
                this.ngayHieuLucField = value;
            }
        }
        
        /// <remarks/>
        public string CoQuanBanHanh {
            get {
                return this.coQuanBanHanhField;
            }
            set {
                this.coQuanBanHanhField = value;
            }
        }
        
        /// <remarks/>
        public string TrichYeu {
            get {
                return this.trichYeuField;
            }
            set {
                this.trichYeuField = value;
            }
        }
        
        /// <remarks/>
        public string NoiDungThamDinh {
            get {
                return this.noiDungThamDinhField;
            }
            set {
                this.noiDungThamDinhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgResult {
        
        private bool successField;
        
        private string messageField;
        
        private string xmlValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string XmlValue {
            get {
                return this.xmlValueField;
            }
            set {
                this.xmlValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GenXML_D01CompletedEventHandler(object sender, GenXML_D01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenXML_D01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenXML_D01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MsgResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MsgResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591